apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: rails
          image: $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPOSITORY:$TAG
          resources:
            requests:
              memory: 500Mi
            limits:
              memory: 1000Mi
        - name: nginx
          volumeMounts:
            - name: nginx-default-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-default-conf
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf
