bases:
  - ../../base
commonLabels:
  env: production
configMapGenerator:
  - name: env
    env: configmaps/env
# NOTE: namePrefix, namespaceをbaseの下に置くとmergeがうまくいかないのでここに書く
namePrefix: cloud-feedbacks-
namespace: cloud-feedbacks-production
patchesStrategicMerge:
  - services/web.yaml
resources:
  - secrets/secret.yaml
